-- ============================================================
-- AGRI-OS MASTER SETUP (v4.0 GLOBAL)
-- Combines: Setup + Hardware Optimization + Log Saving Fixes
-- WARNING: Running this will DELETE ALL EXISTING DATA (Fresh Start)
-- ============================================================

-- 1. CLEANUP (Start Fresh)
DROP TABLE IF EXISTS public.daily_logs CASCADE;
DROP TABLE IF EXISTS public.batches CASCADE;
DROP TABLE IF EXISTS public.systems CASCADE;
DROP TABLE IF EXISTS public.harvest_records CASCADE;
DROP TABLE IF EXISTS public.user_settings CASCADE;
DROP TABLE IF EXISTS public.fields CASCADE;

-- ============================================================
-- 2. CREATE TABLES
-- ============================================================

-- 2.1 DAILY LOGS (Refactored to match Frontend)
CREATE TABLE public.daily_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  
  -- Flexible Identifiers (Can log to a System or a Batch)
  system_id TEXT, -- Optional
  batch_id TEXT,  -- For Microgreens
  target_id TEXT, -- For Hydroponics (usually maps to system_id)
  
  -- Core Status
  system_type TEXT, 
  status TEXT DEFAULT 'active',
  visual_check TEXT,
  notes TEXT,
  
  -- Shared Data
  temp NUMERIC(5,2), -- Air Temp
  humidity NUMERIC(5,2),
  
  -- Hydroponics Specific
  ph NUMERIC(4,2),
  ec NUMERIC(5,2),
  water_temp NUMERIC(5,2),
  water_level TEXT,
  
  -- Microgreens Specific
  watering_status TEXT,
  watering_system TEXT -- Matches JS property Name
);

-- 2.2 BATCHES (Microgreens)
CREATE TABLE public.batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  batch_id TEXT UNIQUE NOT NULL,
  crop TEXT NOT NULL,
  qty INTEGER DEFAULT 1,
  tray_id TEXT,
  sow_date DATE NOT NULL,
  blackout_end_date DATE,
  is_in_blackout BOOLEAN DEFAULT true,
  expected_harvest_date DATE,
  harvest_date DATE,
  status TEXT DEFAULT 'growing',
  yield_grams NUMERIC(10,2) DEFAULT 0,
  cost NUMERIC(10,2) DEFAULT 0,
  revenue NUMERIC(10,2) DEFAULT 0,
  notes TEXT
);

-- 2.3 SYSTEMS (Hydroponics)
CREATE TABLE public.systems (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  system_id TEXT UNIQUE NOT NULL,
  system_type TEXT DEFAULT 'hydroponics',
  crop TEXT NOT NULL DEFAULT 'Lettuce',
  plant_date DATE,
  expected_harvest_date DATE,
  harvest_date DATE,
  current_ph NUMERIC(4,2),
  current_ec NUMERIC(5,2),
  current_temp NUMERIC(5,2),
  status TEXT DEFAULT 'active',
  notes TEXT
);

-- 2.4 HARVEST RECORDS
CREATE TABLE public.harvest_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL,
  crop TEXT NOT NULL,
  harvest_date DATE NOT NULL,
  yield_kg NUMERIC(10,2),
  quality_grade TEXT,
  selling_price_per_kg NUMERIC(10,2),
  total_revenue NUMERIC(10,2),
  notes TEXT
);

-- 2.5 USER SETTINGS
CREATE TABLE public.user_settings (
  user_id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name TEXT,
  email TEXT,
  farm_name TEXT,
  farm_location TEXT,
  farm_area_sqft NUMERIC(10,2),
  soil_type TEXT DEFAULT 'loamy',
  climate_zone TEXT DEFAULT 'delhi',
  push_notifications BOOLEAN DEFAULT true,
  email_notifications BOOLEAN DEFAULT true,
  data_sync BOOLEAN DEFAULT true,
  theme TEXT DEFAULT 'light',
  language TEXT DEFAULT 'en',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ============================================================
-- 3. SECURITY & RLS
-- ============================================================

ALTER TABLE public.daily_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.systems ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.harvest_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own logs" ON public.daily_logs FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own batches" ON public.batches FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own systems" ON public.systems FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own harvests" ON public.harvest_records FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own settings" ON public.user_settings FOR ALL USING (auth.uid() = user_id);

-- ============================================================
-- 4. BRAINS & AUTOMATION (Triggers)
-- ============================================================

-- Function: Auto-update Timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$ LANGUAGE plpgsql;

CREATE TRIGGER update_user_settings_updated_at BEFORE UPDATE ON public.user_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Function: Blackout Logic
CREATE OR REPLACE FUNCTION calculate_blackout_dates() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.sow_date IS NOT NULL THEN
    NEW.blackout_end_date := NEW.sow_date + INTERVAL '3 days';
    NEW.is_in_blackout := (CURRENT_DATE <= (NEW.sow_date + INTERVAL '3 days'));
  END IF;
  RETURN NEW;
END; $$ LANGUAGE plpgsql;

CREATE TRIGGER set_blackout_dates BEFORE INSERT OR UPDATE ON public.batches FOR EACH ROW EXECUTE FUNCTION calculate_blackout_dates();

-- ============================================================
-- 5. PERFORMANCE OPTIMIZATIONS (Indexes)
-- ============================================================
CREATE INDEX idx_logs_user_date ON public.daily_logs(user_id, created_at DESC);
CREATE INDEX idx_logs_batch ON public.daily_logs(batch_id);
CREATE INDEX idx_logs_target ON public.daily_logs(target_id);

CREATE INDEX idx_batches_active ON public.batches(status) WHERE status != 'harvested';
CREATE INDEX idx_systems_active ON public.systems(status) WHERE status != 'harvested';

CREATE INDEX idx_harvests_analytics ON public.harvest_records(crop, harvest_date DESC);

-- ============================================================
-- SETUP COMPLETE
-- ============================================================
