-- ============================================================
-- AGRI-OS MASTER SETUP (v4.1 GLOBAL - INFRA REPAIR)
-- Combines: Core + IoT + CRM + WhatsApp Intelligence + Inventory
-- WARNING: Running this will DELETE ALL EXISTING DATA (Fresh Start)
-- ============================================================

-- 1. CLEANUP (Start Fresh)
DROP TABLE IF EXISTS public.daily_logs CASCADE;
DROP TABLE IF EXISTS public.batches CASCADE;
DROP TABLE IF EXISTS public.systems CASCADE;
DROP TABLE IF EXISTS public.harvest_records CASCADE;
DROP TABLE IF EXISTS public.user_settings CASCADE;
DROP TABLE IF EXISTS public.fields CASCADE;
DROP TABLE IF EXISTS public.customers CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.iot_devices CASCADE;
DROP TABLE IF EXISTS public.sensor_readings CASCADE;
DROP TABLE IF EXISTS public.automation_chains CASCADE;
DROP TABLE IF EXISTS public.automation_logs CASCADE;
DROP TABLE IF EXISTS public.inventory CASCADE;
DROP TABLE IF EXISTS public.market_rates CASCADE;

-- ============================================================
-- 2. CREATE TABLES
-- ============================================================

-- 2.1 USER SETTINGS (Extended)
CREATE TABLE public.user_settings (
  user_id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name TEXT,
  email TEXT,
  farm_name TEXT,
  farm_location TEXT,
  farm_area_sqft NUMERIC(10,2),
  soil_type TEXT DEFAULT 'loamy',
  climate_zone TEXT DEFAULT 'delhi',
  
  -- WhatsApp & Alerts
  whatsapp_alert_number TEXT,
  whatsapp_auto_reply BOOLEAN DEFAULT false,
  whatsapp_auto_reply_msg TEXT DEFAULT 'Dhanyawad! Aapka message mil gaya. Hum jald hi reply karenge. 🌱 - cGrow Team',
  whatsapp_ai_sales BOOLEAN DEFAULT true,
  
  push_notifications BOOLEAN DEFAULT true,
  email_notifications BOOLEAN DEFAULT true,
  data_sync BOOLEAN DEFAULT true,
  theme TEXT DEFAULT 'light',
  language TEXT DEFAULT 'en',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2.2 CUSTOMERS (CRM)
CREATE TABLE public.customers (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    name TEXT NOT NULL,
    whatsapp_number TEXT,
    email TEXT,
    address TEXT,
    city TEXT,
    preferred_variety TEXT,
    marketing_consent BOOLEAN DEFAULT false,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.3 BATCHES (Microgreens)
CREATE TABLE public.batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  batch_id TEXT UNIQUE NOT NULL,
  crop TEXT NOT NULL,
  qty INTEGER DEFAULT 1,
  tray_id TEXT,
  sow_date DATE NOT NULL,
  blackout_end_date DATE,
  is_in_blackout BOOLEAN DEFAULT true,
  expected_harvest_date DATE,
  harvest_date DATE,
  status TEXT DEFAULT 'growing',
  lifecycle_stage TEXT DEFAULT 'nursery',
  seed_weight NUMERIC(10,2) DEFAULT 0,
  yield_grams NUMERIC(10,2) DEFAULT 0,
  cost NUMERIC(10,2) DEFAULT 0,
  revenue NUMERIC(10,2) DEFAULT 0,
  notes TEXT
);

-- 2.4 SYSTEMS (Hydroponics)
CREATE TABLE public.systems (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  system_id TEXT UNIQUE NOT NULL,
  system_type TEXT DEFAULT 'hydroponics',
  crop TEXT NOT NULL DEFAULT 'Lettuce',
  plant_date DATE,
  expected_harvest_date DATE,
  harvest_date DATE,
  current_ph NUMERIC(4,2),
  current_ec NUMERIC(5,2),
  current_temp NUMERIC(5,2),
  status TEXT DEFAULT 'active',
  notes TEXT
);

-- 2.5 DAILY LOGS (Refactored)
CREATE TABLE public.daily_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  
  -- Relational IDs (Aligned with primary tables)
  batch_id BIGINT REFERENCES public.batches(id) ON DELETE SET NULL,  
  target_id BIGINT REFERENCES public.systems(id) ON DELETE SET NULL, 
  system_id TEXT, -- Legacy / Search ID
  
  -- Core Status
  system_type TEXT, 
  status TEXT DEFAULT 'active',
  visual_check TEXT,
  notes TEXT,
  
  -- Metrics
  temp NUMERIC(5,2), 
  humidity NUMERIC(5,2),
  ph NUMERIC(4,2),
  ec NUMERIC(5,2),
  water_temp NUMERIC(5,2),
  water_level TEXT,
  
  -- Operations
  watering_status TEXT,
  watering_system TEXT,
  sync_id TEXT UNIQUE,
  details JSONB DEFAULT '{}'::JSONB,
  observation_tags TEXT[] DEFAULT '{}'
);

-- 2.6 HARVEST RECORDS
CREATE TABLE public.harvest_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL, -- Logical ID (batch_id/system_id text)
  crop TEXT NOT NULL,
  harvest_date DATE NOT NULL,
  yield_kg NUMERIC(10,2),
  quality_grade TEXT,
  selling_price_per_kg NUMERIC(10,2),
  total_revenue NUMERIC(10,2),
  notes TEXT
);

-- 2.7 IOT DEVICES
CREATE TABLE public.iot_devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id TEXT UNIQUE NOT NULL,
  device_name TEXT,
  device_type TEXT DEFAULT 'cGrow-Kit-v1',
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  batch_id BIGINT REFERENCES public.batches(id) ON DELETE SET NULL,
  target_id BIGINT REFERENCES public.systems(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'offline',
  last_seen TIMESTAMPTZ,
  battery_level NUMERIC(5,2),
  firmware_version TEXT,
  wifi_ssid TEXT,
  calibration_data JSONB,
  sensor_config JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.8 SENSOR READINGS
CREATE TABLE public.sensor_readings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id TEXT NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  batch_id BIGINT REFERENCES public.batches(id) ON DELETE SET NULL,
  target_id BIGINT REFERENCES public.systems(id) ON DELETE SET NULL,
  temperature NUMERIC(5,2),
  humidity NUMERIC(5,2),
  ph NUMERIC(4,2),
  ec NUMERIC(6,2),
  water_temp NUMERIC(5,2),
  water_level NUMERIC(6,2),
  soil_moisture_1 NUMERIC(5,2),
  soil_moisture_2 NUMERIC(5,2),
  light_intensity NUMERIC(8,2),
  co2_ppm NUMERIC(6,0),
  reading_time TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.9 CRM AUTOMATION CHAINS
CREATE TABLE public.automation_chains (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  customer_id UUID REFERENCES public.customers(id),
  chain_type TEXT NOT NULL, 
  current_step INTEGER DEFAULT 1,
  status TEXT DEFAULT 'Active', 
  last_sent_at TIMESTAMPTZ DEFAULT NOW(),
  next_scheduled_at TIMESTAMPTZ,
  metadata JSONB DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.10 AUTOMATION LOGS
CREATE TABLE public.automation_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  customer_id UUID REFERENCES public.customers(id),
  chain_id UUID REFERENCES public.automation_chains(id),
  message_content TEXT,
  status TEXT, 
  trigger_type TEXT,
  provider_response JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.11 INVENTORY (SMART SEED VAULT)
CREATE TABLE public.inventory (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    crop_name TEXT NOT NULL,
    quantity_grams NUMERIC DEFAULT 0,
    low_stock_threshold NUMERIC DEFAULT 200,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2.12 MARKET RATES
CREATE TABLE public.market_rates (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    crop_name TEXT UNIQUE NOT NULL,
    price_per_kg NUMERIC(10,2) NOT NULL,
    trend TEXT, -- 'up', 'down', 'stable'
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 3. SECURITY & RLS
-- ============================================================
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.systems ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.harvest_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.iot_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.automation_chains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.automation_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.market_rates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own settings" ON public.user_settings FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own customers" ON public.customers FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own batches" ON public.batches FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own systems" ON public.systems FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own logs" ON public.daily_logs FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own harvests" ON public.harvest_records FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own devices" ON public.iot_devices FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own readings" ON public.sensor_readings FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own chains" ON public.automation_chains FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own auto logs" ON public.automation_logs FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own inventory" ON public.inventory FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Market rates are public" ON public.market_rates FOR SELECT TO authenticated USING (true);

-- ============================================================
-- 4. BRAINS & AUTOMATION (Triggers)
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at_column() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$ LANGUAGE plpgsql;

CREATE TRIGGER update_user_settings_updated_at BEFORE UPDATE ON public.user_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE OR REPLACE FUNCTION calculate_blackout_dates() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.sow_date IS NOT NULL THEN
    NEW.blackout_end_date := NEW.sow_date + INTERVAL '3 days';
    NEW.is_in_blackout := (CURRENT_DATE <= (NEW.sow_date + INTERVAL '3 days'));
  END IF;
  RETURN NEW;
END; $$ LANGUAGE plpgsql;

CREATE TRIGGER set_blackout_dates BEFORE INSERT OR UPDATE ON public.batches FOR EACH ROW EXECUTE FUNCTION calculate_blackout_dates();

-- ============================================================
-- 5. PERFORMANCE OPTIMIZATIONS (Indexes)
-- ============================================================
CREATE INDEX idx_logs_user_date ON public.daily_logs(user_id, created_at DESC);
CREATE INDEX idx_batches_active ON public.batches(status) WHERE status != 'harvested';
CREATE INDEX idx_systems_active ON public.systems(status) WHERE status != 'harvested';
CREATE INDEX idx_sensor_readings_time ON public.sensor_readings(reading_time DESC);
CREATE INDEX idx_auto_chains_next ON public.automation_chains(next_scheduled_at) WHERE status = 'Active';

-- ============================================================
-- SETUP COMPLETE
-- ============================================================
