-- ============================================================
-- AGRI-OS PRODUCTION SETUP (OPTIMIZED v3.1)
-- Combines: Setup + Phase 1-3 Upgrades + Type Fixes + AI Schema
-- Improvements: Removed duplicates, added IF NOT EXISTS guards
-- ============================================================

-- 1. CLEANUP (Start Fresh)
DROP TABLE IF EXISTS public.daily_logs CASCADE;
DROP TABLE IF EXISTS public.batches CASCADE;
DROP TABLE IF EXISTS public.systems CASCADE;
DROP TABLE IF EXISTS public.harvest_records CASCADE;
DROP TABLE IF EXISTS public.user_settings CASCADE;
DROP TABLE IF EXISTS public.fields CASCADE;
DROP TABLE IF EXISTS public.sensor_readings CASCADE;
DROP TABLE IF EXISTS public.crops CASCADE;

-- ============================================================
-- 2. CREATE TABLES (With all "Smart" Columns included)
-- ============================================================

-- 2.1 DAILY LOGS
CREATE TABLE public.daily_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  
  -- Identifiers
  system_id TEXT, -- Made optional (Microgreens use batch_id)
  batch_id TEXT,
  target_id TEXT,
  
  -- Core Status
  system_type TEXT, -- 'Microgreens' or 'Hydroponics'
  status TEXT DEFAULT 'active',
  visual_check TEXT,
  notes TEXT,
  
  -- Hydroponics Data
  ph NUMERIC(4,2),
  ec NUMERIC(5,2),
  temp NUMERIC(5,2), -- Air Temp
  water_temp NUMERIC(5,2),
  water_level TEXT, -- TEXT type (Fixed from numeric)
  dissolved_oxygen NUMERIC(4,2),
  flow_rate NUMERIC(4,2),
  npk_ratio TEXT,
  
  -- Microgreens Data
  humidity NUMERIC(5,2),
  growth_stage TEXT,
  watering_status TEXT,
  watering_system TEXT,
  seed_density NUMERIC(5,2),
  media_type TEXT,
  
  -- Lighting
  light_duration NUMERIC(4,2),
  light_intensity NUMERIC(6,2),
  light_spectrum TEXT,
  
  -- AI-Ready Derived Metrics (Phase 6)
  vpd_kpa NUMERIC(4,2),
  gdd_daily NUMERIC(5,2),
  dli_mol_per_m2 NUMERIC(5,2),
  depletion_pattern TEXT,
  alert_severity TEXT,
  health_score INTEGER,
  vpd_risk_factor TEXT,
  nutrient_warnings_count INTEGER DEFAULT 0,
  
  -- Validation Constraints
  CONSTRAINT check_vpd_range CHECK (vpd_kpa IS NULL OR (vpd_kpa >= 0 AND vpd_kpa <= 5)),
  CONSTRAINT check_gdd_positive CHECK (gdd_daily IS NULL OR gdd_daily >= 0),
  CONSTRAINT check_health_score_range CHECK (health_score IS NULL OR (health_score >= 0 AND health_score <= 100)),
  CONSTRAINT check_alert_severity_valid CHECK (alert_severity IS NULL OR alert_severity IN ('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  CONSTRAINT check_depletion_pattern_valid CHECK (depletion_pattern IS NULL OR depletion_pattern IN ('TRANSPIRATION_DOMINANT', 'NUTRIENT_DOMINANT', 'BALANCED', 'STAGNANT'))
);

COMMENT ON TABLE public.daily_logs IS 'Tracks daily metrics for both Microgreens and Hydroponics with AI-ready derived metrics';
COMMENT ON COLUMN daily_logs.vpd_kpa IS 'Vapor Pressure Deficit in kPa. Optimal: 0.8-1.2 kPa for leafy greens';
COMMENT ON COLUMN daily_logs.gdd_daily IS 'Growing Degree Days accumulated this day';
COMMENT ON COLUMN daily_logs.dli_mol_per_m2 IS 'Daily Light Integral in mol/m²/day. Optimal: 12-17 for lettuce';
COMMENT ON COLUMN daily_logs.health_score IS 'Composite health score (0-100) based on multiple factors';

-- 2.2 BATCHES
CREATE TABLE public.batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  batch_id TEXT NOT NULL,
  
  -- Crop Info
  crop TEXT NOT NULL,
  qty INTEGER DEFAULT 1,
  tray_id TEXT,
  
  -- Dates & Status
  sow_date DATE NOT NULL,
  blackout_end_date DATE,
  is_in_blackout BOOLEAN DEFAULT true,
  expected_harvest_date DATE,
  harvest_date DATE,
  status TEXT DEFAULT 'growing',
  
  -- Financials
  yield_grams NUMERIC(10,2) DEFAULT 0,
  cost NUMERIC(10,2) DEFAULT 0,
  revenue NUMERIC(10,2) DEFAULT 0,
  notes TEXT
);

-- 2.3 SYSTEMS
CREATE TABLE public.systems (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  system_id TEXT NOT NULL,
  system_type TEXT DEFAULT 'hydroponics',
  crop TEXT NOT NULL,
  plant_date DATE,
  expected_harvest_date DATE,
  harvest_date DATE,
  current_ph NUMERIC(4,2),
  current_ec NUMERIC(5,2),
  current_temp NUMERIC(5,2),
  status TEXT DEFAULT 'active',
  notes TEXT
);

-- 2.4 HARVEST RECORDS
CREATE TABLE public.harvest_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL,
  crop TEXT NOT NULL,
  harvest_date DATE NOT NULL,
  yield_kg NUMERIC(10,2),
  quality_grade TEXT,
  selling_price_per_kg NUMERIC(10,2),
  total_revenue NUMERIC(10,2),
  notes TEXT
);

-- 2.5 USER SETTINGS
CREATE TABLE public.user_settings (
  user_id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name TEXT,
  email TEXT,
  farm_name TEXT,
  farm_location TEXT,
  farm_area_sqft NUMERIC(10,2),
  soil_type TEXT DEFAULT 'loamy',
  climate_zone TEXT DEFAULT 'delhi',
  push_notifications BOOLEAN DEFAULT true,
  email_notifications BOOLEAN DEFAULT true,
  data_sync BOOLEAN DEFAULT true,
  theme TEXT DEFAULT 'light',
  language TEXT DEFAULT 'en',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ============================================================
-- 3. ENABLE SECURITY (Row Level Security)
-- ============================================================

ALTER TABLE public.daily_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.systems ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.harvest_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

-- 3.1 POLICIES
CREATE POLICY "Users manage own logs" ON public.daily_logs 
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage own batches" ON public.batches 
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage own systems" ON public.systems 
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage own harvests" ON public.harvest_records 
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage own settings" ON public.user_settings 
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- 4. AUTOMATION TRIGGERS
-- ============================================================

-- 4.1 Update Timestamp Function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = timezone('utc'::text, now());
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_user_settings_updated_at
   BEFORE UPDATE ON public.user_settings
   FOR EACH ROW
   EXECUTE FUNCTION update_updated_at_column();

-- 4.2 Blackout Date Auto-Calculator
CREATE OR REPLACE FUNCTION calculate_blackout_dates()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.sow_date IS NOT NULL THEN
    NEW.blackout_end_date := NEW.sow_date + INTERVAL '3 days';
    NEW.is_in_blackout := (CURRENT_DATE <= (NEW.sow_date + INTERVAL '3 days'));
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_blackout_dates
  BEFORE INSERT OR UPDATE ON public.batches
  FOR EACH ROW
  EXECUTE FUNCTION calculate_blackout_dates();

-- ============================================================
-- 5. PERFORMANCE INDEXES (CONSOLIDATED - No Duplicates)
-- ============================================================

-- Daily Logs Indexes
CREATE INDEX IF NOT EXISTS idx_daily_logs_user 
  ON public.daily_logs(user_id);

CREATE INDEX IF NOT EXISTS idx_daily_logs_created_at 
  ON public.daily_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_daily_logs_batch_id 
  ON public.daily_logs(batch_id) 
  WHERE batch_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_daily_logs_target_id 
  ON public.daily_logs(target_id) 
  WHERE target_id IS NOT NULL;

-- AI/ML Query Indexes
CREATE INDEX IF NOT EXISTS idx_daily_logs_vpd_kpa 
  ON public.daily_logs(vpd_kpa) 
  WHERE vpd_kpa IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_daily_logs_gdd_daily 
  ON public.daily_logs(gdd_daily) 
  WHERE gdd_daily IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_daily_logs_alert_severity 
  ON public.daily_logs(alert_severity) 
  WHERE alert_severity IN ('HIGH', 'CRITICAL');

CREATE INDEX IF NOT EXISTS idx_daily_logs_health_score 
  ON public.daily_logs(health_score) 
  WHERE health_score < 80;

-- Composite index for ML analysis
CREATE INDEX IF NOT EXISTS idx_daily_logs_ml_analysis 
  ON public.daily_logs(batch_id, created_at, vpd_kpa, gdd_daily, health_score) 
  WHERE batch_id IS NOT NULL;

-- Batches Indexes
CREATE INDEX IF NOT EXISTS idx_batches_user 
  ON public.batches(user_id);

CREATE INDEX IF NOT EXISTS idx_batches_status 
  ON public.batches(status) 
  WHERE status != 'harvested';

-- Systems Indexes
CREATE INDEX IF NOT EXISTS idx_systems_user 
  ON public.systems(user_id);

CREATE INDEX IF NOT EXISTS idx_systems_status 
  ON public.systems(status) 
  WHERE status != 'harvested';

-- Harvest Records Indexes
CREATE INDEX IF NOT EXISTS idx_harvests_crop 
  ON public.harvest_records(crop);

CREATE INDEX IF NOT EXISTS idx_harvests_date 
  ON public.harvest_records(harvest_date DESC);

-- ============================================================
-- 6. ANALYZE TABLES FOR QUERY OPTIMIZATION
-- ============================================================

ANALYZE public.daily_logs;
ANALYZE public.batches;
ANALYZE public.systems;
ANALYZE public.harvest_records;
ANALYZE public.user_settings;

-- ============================================================
-- SETUP COMPLETE
-- ============================================================

DO $$
BEGIN
  RAISE NOTICE '✅ Agri-OS Database Setup Complete!';
  RAISE NOTICE '';
  RAISE NOTICE '📊 Tables Created:';
  RAISE NOTICE '  - daily_logs (with AI-ready metrics)';
  RAISE NOTICE '  - batches (with blackout automation)';
  RAISE NOTICE '  - systems';
  RAISE NOTICE '  - harvest_records';
  RAISE NOTICE '  - user_settings';
  RAISE NOTICE '';
  RAISE NOTICE '🔒 Security: RLS enabled with user-scoped policies';
  RAISE NOTICE '⚡ Performance: ' || (SELECT count(*) FROM pg_indexes WHERE schemaname = 'public') || ' indexes created';
  RAISE NOTICE '🤖 AI Ready: VPD, GDD, DLI tracking enabled';
  RAISE NOTICE '🚀 Automation: Blackout dates + timestamps automated';
END $$;
