-- ============================================
-- AGRI-OS COMPLETE DATABASE SETUP
-- Supabase PostgreSQL Schema
-- ============================================

-- 1. CLEANUP (Drop existing tables)
DROP TABLE IF EXISTS public.daily_logs CASCADE;
DROP TABLE IF EXISTS public.batches CASCADE;
DROP TABLE IF EXISTS public.systems CASCADE;
DROP TABLE IF EXISTS public.harvest_records CASCADE;
DROP TABLE IF EXISTS public.user_settings CASCADE;
DROP TABLE IF EXISTS public.fields CASCADE;

-- ============================================
-- 2. CREATE TABLES
-- ============================================

-- 2.1 DAILY LOGS (pH, EC, Temperature tracking + NEW Two-Column Tracker Fields)
CREATE TABLE public.daily_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  system_id TEXT NOT NULL,
  system_type TEXT, -- 'Microgreens' or 'Hydroponics'
  
  -- Common fields
  temp NUMERIC(5,2), -- Room temperature
  notes TEXT,
  status TEXT DEFAULT 'active',
  
  -- HYDROPONICS-SPECIFIC FIELDS
  ph NUMERIC(4,2),
  ec NUMERIC(5,2),
  water_temp NUMERIC(5,2), -- NEW: Water temperature
  water_level TEXT, -- NEW: 'OK', 'Top-up Needed', 'Overflowing'
  
  -- MICROGREENS-SPECIFIC FIELDS
  humidity NUMERIC(5,2), -- NEW: Humidity percentage
  growth_stage TEXT, -- NEW: 'Germination', 'Blackout', 'Under Lights', 'Harvest Ready'
  watering_status TEXT, -- NEW: 'None', 'Misted', 'Bottom Watered', 'Over-watered'
  visual_check TEXT -- NEW: 'Looks Good', 'Mold Detected', 'Wilting', 'Yellowing'
);

-- 2.2 BATCHES (Microgreens batches)
CREATE TABLE public.batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  batch_id TEXT UNIQUE NOT NULL,
  crop TEXT NOT NULL,
  tray_id TEXT,
  sow_date DATE NOT NULL,
  expected_harvest_date DATE,
  harvest_date DATE,
  yield_grams NUMERIC(10,2) DEFAULT 0,
  cost NUMERIC(10,2) DEFAULT 0,
  revenue NUMERIC(10,2) DEFAULT 0,
  status TEXT DEFAULT 'growing', -- 'growing', 'harvested', 'sold'
  notes TEXT
);

-- 2.3 SYSTEMS (Hydroponics systems)
CREATE TABLE public.systems (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  system_id TEXT UNIQUE NOT NULL,
  system_type TEXT DEFAULT 'hydroponics', -- 'hydroponics', 'nft', 'dwc'
  crop TEXT NOT NULL,
  plant_date DATE,
  expected_harvest_date DATE,
  harvest_date DATE,
  current_ph NUMERIC(4,2),
  current_ec NUMERIC(5,2),
  current_temp NUMERIC(5,2),
  status TEXT DEFAULT 'active', -- 'active', 'harvested', 'maintenance'
  notes TEXT
);

-- 2.4 HARVEST RECORDS (Track all harvests)
CREATE TABLE public.harvest_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  source_type TEXT NOT NULL, -- 'microgreens' or 'hydroponics'
  source_id TEXT NOT NULL, -- batch_id or system_id
  crop TEXT NOT NULL,
  harvest_date DATE NOT NULL,
  yield_kg NUMERIC(10,2),
  quality_grade TEXT, -- 'A', 'B', 'C'
  selling_price_per_kg NUMERIC(10,2),
  total_revenue NUMERIC(10,2),
  notes TEXT
);

-- 2.5 FIELDS (Farm field management)
CREATE TABLE public.fields (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  field_name TEXT NOT NULL,
  area_sqft NUMERIC(10,2),
  soil_type TEXT, -- 'loamy', 'sandy', 'clayey', 'black', 'red'
  location TEXT,
  latitude NUMERIC(10,6),
  longitude NUMERIC(10,6),
  current_crop TEXT,
  plant_date DATE,
  status TEXT DEFAULT 'active',
  notes TEXT
);

-- 2.6 USER SETTINGS (User preferences)
CREATE TABLE public.user_settings (
  user_id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name TEXT,
  email TEXT,
  farm_name TEXT,
  farm_location TEXT,
  farm_area_sqft NUMERIC(10,2),
  soil_type TEXT DEFAULT 'loamy',
  climate_zone TEXT DEFAULT 'delhi',
  push_notifications BOOLEAN DEFAULT true,
  email_notifications BOOLEAN DEFAULT true,
  data_sync BOOLEAN DEFAULT true,
  theme TEXT DEFAULT 'light',
  language TEXT DEFAULT 'en',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ============================================
-- 3. CREATE INDEXES (for performance)
-- ============================================

CREATE INDEX idx_daily_logs_user_id ON public.daily_logs(user_id);
CREATE INDEX idx_daily_logs_system_id ON public.daily_logs(system_id);
CREATE INDEX idx_daily_logs_created_at ON public.daily_logs(created_at DESC);

CREATE INDEX idx_batches_user_id ON public.batches(user_id);
CREATE INDEX idx_batches_status ON public.batches(status);
CREATE INDEX idx_batches_batch_id ON public.batches(batch_id);

CREATE INDEX idx_systems_user_id ON public.systems(user_id);
CREATE INDEX idx_systems_status ON public.systems(status);
CREATE INDEX idx_systems_system_id ON public.systems(system_id);

CREATE INDEX idx_harvest_records_user_id ON public.harvest_records(user_id);
CREATE INDEX idx_harvest_records_harvest_date ON public.harvest_records(harvest_date DESC);

CREATE INDEX idx_fields_user_id ON public.fields(user_id);

-- ============================================
-- 4. ENABLE ROW LEVEL SECURITY (RLS)
-- ============================================

ALTER TABLE public.daily_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.systems ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.harvest_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 5. CREATE RLS POLICIES
-- ============================================

-- 5.1 DAILY LOGS POLICIES
CREATE POLICY "Users can view own logs" 
  ON public.daily_logs FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own logs" 
  ON public.daily_logs FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own logs" 
  ON public.daily_logs FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own logs" 
  ON public.daily_logs FOR DELETE 
  USING (auth.uid() = user_id);

-- 5.2 BATCHES POLICIES
CREATE POLICY "Users can view own batches" 
  ON public.batches FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own batches" 
  ON public.batches FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own batches" 
  ON public.batches FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own batches" 
  ON public.batches FOR DELETE 
  USING (auth.uid() = user_id);

-- 5.3 SYSTEMS POLICIES
CREATE POLICY "Users can view own systems" 
  ON public.systems FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own systems" 
  ON public.systems FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own systems" 
  ON public.systems FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own systems" 
  ON public.systems FOR DELETE 
  USING (auth.uid() = user_id);

-- 5.4 HARVEST RECORDS POLICIES
CREATE POLICY "Users can view own harvest records" 
  ON public.harvest_records FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own harvest records" 
  ON public.harvest_records FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own harvest records" 
  ON public.harvest_records FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own harvest records" 
  ON public.harvest_records FOR DELETE 
  USING (auth.uid() = user_id);

-- 5.5 FIELDS POLICIES
CREATE POLICY "Users can view own fields" 
  ON public.fields FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own fields" 
  ON public.fields FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own fields" 
  ON public.fields FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own fields" 
  ON public.fields FOR DELETE 
  USING (auth.uid() = user_id);

-- 5.6 USER SETTINGS POLICIES
CREATE POLICY "Users can view own settings" 
  ON public.user_settings FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own settings" 
  ON public.user_settings FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own settings" 
  ON public.user_settings FOR UPDATE 
  USING (auth.uid() = user_id);

-- ============================================
-- 6. CREATE FUNCTIONS (Optional helpers)
-- ============================================

-- Function to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for user_settings
CREATE TRIGGER update_user_settings_updated_at
    BEFORE UPDATE ON public.user_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- 7. SAMPLE DATA (Optional - for testing)
-- ============================================

-- Uncomment to insert sample data after user signup
/*
INSERT INTO public.batches (user_id, batch_id, crop, tray_id, sow_date, expected_harvest_date, status)
VALUES 
  (auth.uid(), 'MG-001', 'Radish (Mooli)', 'T1', CURRENT_DATE, CURRENT_DATE + INTERVAL '7 days', 'growing'),
  (auth.uid(), 'MG-002', 'Fenugreek (Methi)', 'T2', CURRENT_DATE, CURRENT_DATE + INTERVAL '10 days', 'growing');

INSERT INTO public.systems (user_id, system_id, crop, plant_date, expected_harvest_date, current_ph, current_ec, status)
VALUES 
  (auth.uid(), 'NFT-001', 'Lettuce', CURRENT_DATE, CURRENT_DATE + INTERVAL '30 days', 6.0, 1.8, 'active');
*/

-- ============================================
-- SETUP COMPLETE!
-- ============================================
-- Next steps:
-- 1. Run this script in Supabase SQL Editor
-- 2. Verify tables are created in Table Editor
-- 3. Test RLS policies by inserting data
-- 4. Connect your app using Supabase client
-- ============================================
